import Icon from '../components/Icon'
import { Empty, PageHeader } from '../components/UI'
import { getAnalytics, minutesLabel, shortDate, titleCase } from '../lib'
export default function Dashboard({ data, navigate }) {
  const a = getAnalytics(data), metrics = [['Sessions', a.sessions, 'This week', 'book'], ['Training time', minutesLabel(a.minutes), 'This week', 'clock'], ['Primary position', a.topPosition, 'Most documented', 'target'], ['Problem area', a.problem, 'From sparring notes', 'sparring'], ['Technique confidence', a.confidence ? `${a.confidence.toFixed(1)} / 5` : 'Not enough data', 'Library average', 'techniques']]
  const weekStart = new Date(); weekStart.setHours(0, 0, 0, 0); weekStart.setDate(weekStart.getDate() - ((weekStart.getDay() + 6) % 7))
  const studiedThisWeek = data.study.filter((item) => new Date(`${item.date}T12:00:00`) >= weekStart && !['To watch', 'Discarded'].includes(item.status)).length
  const drillItems = data.study.filter((item) => item.status === 'Drill this').length
  const latestStudy = [...data.study].sort((left, right) => String(right.date).localeCompare(String(left.date)))[0]
  return <><PageHeader eyebrow="Training overview" title="Your work, made visible." description="Review the patterns. Choose the next problem worth solving." action={<button className="primary desktop-action" onClick={() => navigate('log')}><Icon name="plus" size={17}/> Log session</button>} />
    <section className="metric-grid">{metrics.map(([label, value, note, icon]) => <article className="metric" key={label}><div className="metric-top"><span>{label}</span><Icon name={icon} size={18}/></div><strong>{value}</strong><small>{note}</small></article>)}</section>
    <section className="focus-card"><div className="focus-icon"><Icon name="target"/></div><div><p className="eyebrow">Recommended focus</p><h2>{a.focus}</h2><p>{a.problem !== 'Not enough data' ? 'This position appears most often in your sparring problems. Make it the question you bring to the next session.' : 'Your focus will become clearer as you capture techniques and sparring observations.'}</p></div><button className="text-button" onClick={() => navigate(a.problem !== 'Not enough data' ? 'sparring' : 'log')}>Add evidence <Icon name="chevron" size={15}/></button></section>
    <section className="study-summary"><div><p className="eyebrow">Study room</p><h2>{latestStudy ? latestStudy.title : 'No study items yet'}</h2><p>{latestStudy ? `Latest · ${shortDate(latestStudy.date)}${latestStudy.instructorOrChannel ? ` · ${latestStudy.instructorOrChannel}` : ''}` : 'Capture one useful video and turn it into a plan for the mat.'}</p></div><div className="study-summary-count"><strong>{studiedThisWeek}</strong><span>Studied this week</span></div><div className="study-summary-count"><strong>{drillItems}</strong><span>Marked “Drill this”</span></div><button className="text-button" onClick={() => navigate('study')}>{latestStudy ? 'Open study room' : 'Add a video'} <Icon name="chevron" size={15}/></button></section>
    <section className="section-block"><div className="section-title"><div><p className="eyebrow">Latest work</p><h2>Recent sessions</h2></div>{data.sessions.length > 0 && <button className="text-button" onClick={() => navigate('log')}>Add session <Icon name="plus" size={15}/></button>}</div>
      {data.sessions.length === 0 ? <Empty title="Your notebook is ready" text="Log your first training session. Keep it honest, concise, and useful to your future self." action={<button className="secondary" onClick={() => navigate('log')}>Log first session</button>} /> : <div className="session-list">{data.sessions.slice(0, 5).map((s) => <article className="session-row" key={s.id}><div className="date-block"><strong>{shortDate(s.date).split(' ')[0]}</strong><span>{shortDate(s.date).split(' ')[1]}</span></div><div><div className="row-title"><h3>{titleCase(s.type)}</h3><span className="pill">{s.uniform === 'nogi' ? 'No-Gi' : 'Gi'}</span></div><p>{s.lesson || s.worked || 'Session logged without a main lesson.'}</p></div><div className="duration">{minutesLabel(Number(s.duration))}<small>{titleCase(s.intensity)}</small></div></article>)}</div>}
    </section></>
}
