import { useState } from 'react'
import { Field, PageHeader, Segmented } from '../components/UI'
import { SESSION_TYPES, today, uid } from '../lib'
const blank = () => ({ date: today(), type: 'class', uniform: 'gi', duration: 90, intensity: 'moderate', physical: 'fresh', techniques: '', worked: '', failed: '', lesson: '' })
export default function LogSession({ add, navigate }) {
  const [form, setForm] = useState(blank), set = (key, value) => setForm((f) => ({ ...f, [key]: value }))
  const submit = (e) => { e.preventDefault(); add('sessions', { ...form, id: uid(), createdAt: new Date().toISOString() }); navigate('dashboard') }
  return <><PageHeader eyebrow="Session log" title="Capture the useful details." description="Write for the practitioner you will be six months from now." />
    <form className="panel form-grid" onSubmit={submit}><Field label="Date"><input required type="date" value={form.date} onChange={(e) => set('date', e.target.value)}/></Field><Field label="Session type"><select value={form.type} onChange={(e) => set('type', e.target.value)}>{SESSION_TYPES.map((o) => <option key={o} value={o.toLowerCase()}>{o}</option>)}</select></Field><Field label="Ruleset / uniform" wide><Segmented name="uniform" options={['Gi', 'No-Gi']} value={form.uniform} onChange={(v) => set('uniform', v === 'no-gi' ? 'nogi' : v)}/></Field><Field label="Duration (minutes)"><input required min="1" type="number" value={form.duration} onChange={(e) => set('duration', e.target.value)}/></Field><Field label="Intensity"><select value={form.intensity} onChange={(e) => set('intensity', e.target.value)}>{['Light','Moderate','Hard','Brutal'].map((o)=><option key={o} value={o.toLowerCase()}>{o}</option>)}</select></Field><Field label="Physical state" wide><Segmented name="physical" options={['Fresh','Tired','Sore','Injured']} value={form.physical} onChange={(v) => set('physical', v)}/></Field>
      {[['techniques','Techniques learned','Names, key details, or sequences shown.'],['worked','What worked','Where did your decisions or mechanics hold up?'],['failed','What failed','Be specific. Position, reaction, and consequence.'],['lesson','Main lesson','The one idea you want to carry into the next session.']].map(([key,label,placeholder]) => <Field key={key} label={label} wide><textarea rows="3" value={form[key]} placeholder={placeholder} onChange={(e)=>set(key,e.target.value)}/></Field>)}<div className="form-actions wide"><button type="button" className="ghost" onClick={()=>navigate('dashboard')}>Cancel</button><button className="primary" type="submit">Save session</button></div></form></>
}
