import { useMemo, useState } from 'react'
import Icon from '../components/Icon'
import { DeleteButton, Empty, Field, PageHeader, Segmented } from '../components/UI'
import { POSITIONS, TECHNIQUE_TYPES, uid } from '../lib'
const blank = { name: '', position: 'Standing', type: 'Takedown', uniform: 'both', confidence: 3, notes: '', mistakes: '' }
export default function Techniques({ data, add, remove }) {
  const [editing, setEditing] = useState(false), [form, setForm] = useState(blank), [search, setSearch] = useState(''), [position, setPosition] = useState('All'), set = (k,v)=>setForm((f)=>({...f,[k]:v}))
  const items = useMemo(()=>data.techniques.filter((t)=>(position==='All'||t.position===position)&&`${t.name} ${t.notes}`.toLowerCase().includes(search.toLowerCase())),[data.techniques,search,position])
  const submit=(e)=>{e.preventDefault();add('techniques',{...form,id:uid()});setForm(blank);setEditing(false)}
  return <><PageHeader eyebrow="Technical reference" title="Techniques library" description="Store details you can recall under pressure—not an encyclopedia." action={<button className="primary" onClick={()=>setEditing(!editing)}><Icon name={editing?'close':'plus'} size={17}/>{editing?'Close':'Add technique'}</button>}/>
    {editing&&<form className="panel form-grid compact" onSubmit={submit}><Field label="Technique name" wide><input required autoFocus value={form.name} placeholder="e.g. Knee-cut pass" onChange={(e)=>set('name',e.target.value)}/></Field><Field label="Position"><select value={form.position} onChange={(e)=>set('position',e.target.value)}>{POSITIONS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Type"><select value={form.type} onChange={(e)=>set('type',e.target.value)}>{TECHNIQUE_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Applicability" wide><Segmented name="tech-uniform" options={['Gi','No-Gi','Both']} value={form.uniform} onChange={(v)=>set('uniform',v==='no-gi'?'nogi':v)}/></Field><Field label={`Confidence — ${form.confidence}/5`} wide><input className="range" type="range" min="1" max="5" value={form.confidence} onChange={(e)=>set('confidence',e.target.value)}/></Field><Field label="Notes" wide><textarea rows="3" value={form.notes} onChange={(e)=>set('notes',e.target.value)} placeholder="Mechanics, grips, timing, reactions…"/></Field><Field label="Common mistakes" wide><textarea rows="2" value={form.mistakes} onChange={(e)=>set('mistakes',e.target.value)} placeholder="What makes this fail?"/></Field><div className="form-actions wide"><button className="primary" type="submit">Save technique</button></div></form>}
    <div className="filters"><label className="search"><Icon name="search" size={17}/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search techniques"/></label><select value={position} onChange={(e)=>setPosition(e.target.value)}><option>All</option>{POSITIONS.map(x=><option key={x}>{x}</option>)}</select></div>
    {items.length===0?<Empty title={data.techniques.length?'No matching techniques':'Build your working library'} text={data.techniques.length?'Try a broader search or another position.':'Save mechanics, reactions, and mistakes while the details are still fresh.'}/>:<div className="card-grid">{items.map(t=><article className="tech-card" key={t.id}><div className="card-head"><span className="pill accent">{t.position}</span><DeleteButton onClick={()=>remove('techniques',t.id)}/></div><h3>{t.name}</h3><p className="meta">{t.type} · {t.uniform==='nogi'?'No-Gi':t.uniform==='both'?'Gi & No-Gi':'Gi'}</p>{t.notes&&<p>{t.notes}</p>}<div className="confidence"><span>Confidence</span><div>{[1,2,3,4,5].map(n=><i className={n<=t.confidence?'filled':''} key={n}/>)}</div><strong>{t.confidence}/5</strong></div>{t.mistakes&&<div className="mistake"><span>Watch for</span><p>{t.mistakes}</p></div>}</article>)}</div>}</>
}
