import { useState } from 'react'
import './App.css'
import Icon from './components/Icon'
import { useNotebook } from './hooks/useNotebook'
import Dashboard from './screens/Dashboard'
import LogSession from './screens/LogSession'
import Techniques from './screens/Techniques'
import Sparring from './screens/Sparring'
import GamePlan from './screens/GamePlan'
import Settings from './screens/Settings'
const nav=[['dashboard','Dashboard'],['log','Log session'],['techniques','Techniques'],['sparring','Sparring notes'],['plan','Game plan'],['settings','Settings']]
export default function App(){const[view,setView]=useState('dashboard'),[menu,setMenu]=useState(false);const notebook=useNotebook();const navigate=v=>{setView(v);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})};const screens={dashboard:<Dashboard data={notebook.data} navigate={navigate}/>,log:<LogSession add={notebook.add} navigate={navigate}/>,techniques:<Techniques data={notebook.data} add={notebook.add} remove={notebook.remove}/>,sparring:<Sparring data={notebook.data} add={notebook.add} remove={notebook.remove}/>,plan:<GamePlan data={notebook.data} setData={notebook.setData}/>,settings:<Settings {...notebook}/>};return <div className="app-shell"><aside className={menu?'open':''}><div className="brand"><div className="brand-mark">B</div><div><strong>BJJ</strong><span>Notebook</span></div><button className="mobile-close" onClick={()=>setMenu(false)}><Icon name="close"/></button></div><nav>{nav.map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>navigate(key)}><Icon name={key}/><span>{label}</span>{view===key&&<i/>}</button>)}</nav><div className="side-note"><span>TRAIN WITH INTENT</span><p>Observe. Record.<br/>Adjust. Repeat.</p></div></aside>{menu&&<button className="scrim" aria-label="Close menu" onClick={()=>setMenu(false)}/>}<main><div className="mobile-bar"><button onClick={()=>setMenu(true)} aria-label="Open menu"><Icon name="menu"/></button><span>BJJ <b>NOTEBOOK</b></span><button onClick={()=>navigate('log')} aria-label="Log session"><Icon name="plus"/></button></div><div className="content">{screens[view]}</div><footer><span>BJJ Notebook</span><p>Built for deliberate practice. Your data stays on this device.</p></footer></main><button className="mobile-fab" onClick={()=>navigate('log')} aria-label="Log session"><Icon name="plus" size={24}/></button></div>}
